package com.example.color

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.ByteArrayOutputStream
import java.io.DataOutputStream
import java.io.File
import java.io.FileOutputStream
import java.nio.charset.StandardCharsets

object AseExporter {

    /**
     * Generates a binary Adobe Swatch Exchange (.ase) file payload from a list of HSL colors.
     */
    fun generateAseBytes(colors: List<HslColor>, paletteTitle: String = "Huesmith Palette"): ByteArray {
        val bos = ByteArrayOutputStream()
        val dos = DataOutputStream(bos)

        // 1. Signature "ASEF" (4 bytes)
        dos.write("ASEF".toByteArray(StandardCharsets.US_ASCII))

        // 2. Version 1.0 (Major = 1, Minor = 0) (4 bytes)
        dos.writeShort(1)
        dos.writeShort(0)

        // 3. Number of blocks (4 bytes, Big Endian)
        dos.writeInt(colors.size)

        // 4. Color Blocks
        colors.forEachIndexed { index, hsl ->
            val rgb = hsl.toRgb()
            val hex = hsl.toHex()
            val swatchName = "$paletteTitle - Color ${index + 1} ($hex)"

            // Color block type: 0x0001 (2 bytes)
            dos.writeShort(0x0001)

            // Calculate payload length:
            // Name length in UTF-16 code units (including null terminator): 2 bytes
            // Name UTF-16BE + 0x0000: (swatchName.length + 1) * 2 bytes
            // Color space "RGB ": 4 bytes
            // Float32 values for R, G, B: 3 * 4 = 12 bytes
            // Color type (0x0000 = Global, 0x0002 = Normal): 2 bytes
            val nameCharCount = swatchName.length + 1
            val blockPayloadLength = 2 + (nameCharCount * 2) + 4 + 12 + 2

            // Write block length (4 bytes)
            dos.writeInt(blockPayloadLength)

            // Write name char count (2 bytes)
            dos.writeShort(nameCharCount)

            // Write name as UTF-16BE + null terminator
            for (ch in swatchName) {
                dos.writeChar(ch.code)
            }
            dos.writeChar(0) // null terminator

            // Color space: "RGB " (4 bytes)
            dos.write("RGB ".toByteArray(StandardCharsets.US_ASCII))

            // R, G, B floats normalized between 0.0f and 1.0f (12 bytes)
            dos.writeFloat(rgb.r.coerceIn(0, 255) / 255f)
            dos.writeFloat(rgb.g.coerceIn(0, 255) / 255f)
            dos.writeFloat(rgb.b.coerceIn(0, 255) / 255f)

            // Color type: 0x0000 (Global swatch)
            dos.writeShort(0x0000)
        }

        dos.flush()
        return bos.toByteArray()
    }

    suspend fun saveAseFile(context: Context, colors: List<HslColor>, paletteTitle: String): Uri? =
        withContext(Dispatchers.IO) {
            val bytes = generateAseBytes(colors, paletteTitle)
            val exportsDir = File(context.cacheDir, "exports").apply { mkdirs() }
            val sanitizedName = paletteTitle.replace("[^a-zA-Z0-9_-]".toRegex(), "_").lowercase()
            val file = File(exportsDir, "huesmith_${sanitizedName}.ase")

            FileOutputStream(file).use { out ->
                out.write(bytes)
            }

            FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
        }

    fun shareAseFile(context: Context, uri: Uri, paletteTitle: String) {
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/x-adobe-swatch-exchange"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(
                Intent.EXTRA_TEXT,
                "Adobe Swatch Exchange (.ase) file for '$paletteTitle'\nGenerated by Huesmith Color Craftsman"
            )
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, "Share Adobe Swatch (.ase)"))
    }

    fun exportAndShareAse(
        context: Context,
        scope: kotlinx.coroutines.CoroutineScope,
        colors: List<HslColor>,
        paletteTitle: String
    ) {
        scope.launch(Dispatchers.Main) {
            val uri = saveAseFile(context, colors, paletteTitle)
            uri?.let { shareAseFile(context, it, paletteTitle) }
        }
    }
}
